mi_portal_web/mi_portal_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),  # Add this line
]

mi_portal_web/my_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name='home'), # El que tiene solo comillas es la página principal
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),  # Add this line
    path('blog/', views.blog, name='blog'),  # Add this line
    path('services/', views.services, name='services'),  # Add this line
    path('our_teams/', views.our_teams, name='our_teams'),  # Add this line
    path('portafolio/', views.portafolio, name='portafolio'),  # Add this line
    path('testimonios/', views.testimonios, name='testimonios'),  # Add this line
    path('events_register/', views.event_register_view, name='event_register'),  # Add this line
    path('events_list/', views.event_list_view, name='event_list'),  # Add this line
    path('portafolio_register/', views.portafolio_register_view, name='portafolio_register'),# Add this line
    path('testimonio_register/', views.testimonio_register_view, name='testimonio_register'),  # Add this line
    
]

mi_portal_web/my_app/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    
class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    fecha = models.DateTimeField()
    capacidad = models.IntegerField()
    
class Porta(models.Model):
    nombre_proyecto = models.CharField(max_length=100)
    descripcion = models.TextField()
    image = models.ImageField(default='static/img')
    link = models.URLField(blank=True, null=True)

class Testimonio(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    puesto = models.CharField(max_length=100, default='Puesto Desconocido')
    empresa = models.CharField(max_length=100, default='Empresa Desconocida')


    def __str__(self):
        return self.nombre
    
    

mi_portal_web/my_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .form import ContactForm, EventForm, PortaForm, TestimonioForm
from .models import Event 
from .models import Porta 
from .models import Testimonio

def home(request):
    # return HttpResponse("bienvenido a tu página.")
    return render (request, 'myapp/home.html')

def about (request):
    # return HttpResponse("Estás en la sección 'Acerca de'.")
    return render (request, 'myapp/about.html')

# def contact(request):
#     # return HttpResponse("Estás en la sección 'Contacto'.")
#     return render (request, 'myapp/contact.html')

def contact(request):
    if request.method == 'POST':
     form = ContactForm(request.POST)
     if form.is_valid():
        form.save()
        return redirect('home')
    else:
        form = ContactForm()
    return render(request,'myapp/contact.html',{'form': form})


def blog (request):
    # return HttpResponse("Estás en la sección 'Blog'.")
    return render (request, 'myapp/blog.html')

def services (request):
    # return HttpResponse("Estás en la sección 'Services'.")
    return render (request, 'myapp/services.html')

def our_teams (request):
    return render (request, 'myapp/our_teams.html')

# def portafolio (request):
#     return render (request, 'myapp/portafolio.html')

# def portafolio (request):
#     projects =[
#         {'name': 'Pagina de Restaurant', 'description': 'Proyecto para cadena de restaurantes mexicanos', 'image': '' },
#         {'name': 'Pagina de Inmobiliarias', 'description': 'Proyecto para venta de casas', 'image': '' },
#         {'title': 'Pagina de Escuelas', 'description': 'Descripción del proyecto 3'},
#         #... more projects here
#     ]
#     return render(request, 'myapp/portafolio.html', {'projects': projects})


# def testimonios (request):

#     testimonios_data =[
#         {'Nombre': "Roberto", 'Puesto': "CEO", 'testimonio': 'Excelente servicio' },
#         {'Nombre': "Roberto", 'Puesto': "CEO", 'testimonio': 'Excelente servicio' },
#         #... more projects here
#     ]
#     return render(request, 'myapp/testimonios.html', {'testimonios': testimonios_data})

def event_register_view(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event_list')
    else:
        form = EventForm()
    return render(request, 'myapp/event_register.html', {'form': form})

def event_list_view(request):
    events = Event.objects.all()  #Select  * form Events
    return render (request, 'myapp/event_list.html', {'events': events} )


# Crear el modelo para portafolio y testimonios 
# Crear formularios alta de testimonios y portafolio

# Portafolio
def portafolio_register_view(request):
    if request.method == 'POST':
        form = PortaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('portafolio')
    else:
        form = PortaForm()
    return render(request, 'myapp/portafolio_register.html', {'form': form})


def portafolio (request):
    projects = Porta.objects.all()
    return render(request, 'myapp/portafolio.html', {'projects': projects})

# Testimonios
def testimonio_register_view(request):
    if request.method == 'POST':
        form = TestimonioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('testimonios')
    else:
        form = TestimonioForm()
    return render(request, 'myapp/testimonio_register.html', {'form': form})

def testimonios (request):
    testimonios_data = Testimonio.objects.all()
    return render(request, 'myapp/testimonios.html', {'testimonios': testimonios_data})

mi_portal_web/my_app/templates/myapp/_form.html
{% csrf_token %}
{%for field in form%}
    <div class= "form-group">
        <label for="{{field.id_for_label}}">{{field.label}}</label>
        {{field}}
        {% if field.errors %}
            <div class="alert alert-danger" role="alert">
                {{field.errors}}
            </div>
        {% endif %}
    </div>
{% endfor %}

mi_portal_web/my_app/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %} home {% endblock title%}
{% load static %}

{% block content %}
    <h1>Bienvenidos a esta página</h1>
    <p>Esta es la página acerca de</p>
    <p class="d-inline-flex gap-1">
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          Link with href
        </a>
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Button with data-bs-target
        </button>
      </p>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
          Some placeholder content for the collapse component. This panel is hidden by default but revealed when the user activates the relevant trigger.
        </div>
      </div>

      {% endblock %}

mi_portal_web/my_app/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Mi Portal Web{% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    
</head>
<body>
{% comment %} inicio menu {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Mi portal Web</a>  {% comment %}cambiar a una imagen con logo{% endcomment %}
          <img src="" class="img-fluid" alt="...">

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'our_teams' %}">Nuestro Equipo</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contacto</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'portafolio' %}">Portafolio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'services' %}">Servicios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'testimonios' %}">Testimonios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'event_register' %}">Eventos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'portafolio_register' %}">Registro Portafolio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'testimonio_register' %}">Registro Testimonios</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% comment %} FIN menu {% endcomment %}


    {% comment %} INICIA main content {% endcomment %}

    <div class= "container md">
        {% block content %}
        {% endblock content %}
    </div>
    {% comment %} FIN main content {% endcomment %}

    {% comment %} INICIA SCRIPTS MENU {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

mi_portal_web/my_app/templates/myapp/blog.html
{% extends 'myapp/base.html' %}
{% block title %} home {% endblock title%}
{% load static %}

{% block content %}
    <h1>Bienvenidos a esta página</h1>
    <p>Esta es la página del Blog</p>
    
    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
{% endblock %}

mi_portal_web/my_app/templates/myapp/contact.html
{% extends 'myapp/base.html' %}
{% block title %} Contact {% endblock title%}
{% load static %}

{% block content %}
<h1>Bienvenidos a esta página de contacto</h1>
<form action="post" action= "{{ contact }}"> 
    {% csrf_token %}
  <div class="form-group">
    <label for="id_name">Name</label>
    {{form.name}}
  </div>

  <div class="form-group">
    <label for="id_email">Email</label>
    {{form.email}}
  </div>

  <div class="form-group">
    <label for="id_message">Message</label>
    {{form.message}}
  </div>
  <button type="submit" class="btn btn-primary">Send</button>

</form>

{% endblock content%}

mi_portal_web/my_app/templates/myapp/event_list.html
{% extends 'myapp/base.html' %}
{% block title %} Lista de Eventos {% endblock title%}
{% load static %}

{% block content %}
<h2> Lista de Eventos</h2>

<table>
    <thead>
        <th>ID</th>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha</th>
        <th>Capacidad</th>
    </thead>
    <tbody>
        {% for event in events %}
        <tr>
            <td>{{ event.id }}</td>
            <td>{{ event.name }}</td>
            <td>{{ event.description }}</td>
            <td>{{ event.fecha }}</td>
            <td>{{ event.capacidad }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

mi_portal_web/my_app/templates/myapp/event_register.html
{% extends 'myapp/base.html' %}
{% block title %} Registro de Eventos {% endblock title%}
{% load static %}


{% block content %}
<h2>Registrar Evento</h2>
<form method="post">
    {% include 'myapp/_form.html' %}
    <button type="submit" class = "btn btn-primary">Guardar</button>
</form>

{% endblock %}

mi_portal_web/my_app/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block title %} home {% endblock title%}
{% load static %}

{% block content %}

    <h1>Bienvenidos a esta página Mi portal Web</h1>
    <p>Esta es la página de Inicio</p>
    <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'css/img/img1.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'css/img/img2.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'css/img/img3.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

{% endblock %}

mi_portal_web/my_app/templates/myapp/our_teams.html
{% extends 'myapp/base.html' %}
{% block title %} home {% endblock title%}
{% load static %}

{% block content %}
    <h1>Bienvenidos a esta página</h1>
    <p>Esta es la página de Nuestro Equipo</p>
    <div class="card">
        <img src="{% static 'css/img/team.jpg' %}" class="d-block w-100" alt="...">
      
        <div class="card-body">
          <h5 class="card-title">Nuestro Equipo</h5>
          <p class="card-text">Innovación y metas claras nos caracteriza</p>
        
        </div>
      </div>


{% endblock %}

mi_portal_web/my_app/templates/myapp/portafolio.html
{% extends 'myapp/base.html' %}
{% block title%} Portafolio {% endblock title %}
{% load static %}
{%block content%}
<h1>Portafolio</h1>
<div class="row">
    {%for  project in projects%}
    <div class="card" style="width: 18rem;">
        <img src={{ project.image }} class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{project.name  }}</h5>
          <p class="card-text">{{ project.description }}</p>
          <a href={{ project.url }}  target="_blank" class="btn btn-primary">Visitar el sitio</a>
        </div>
      </div>


    {%endfor %}
</div>

{% endblock content %}

mi_portal_web/my_app/templates/myapp/portafolio_register.html
{% extends 'myapp/base.html' %}
{% block title %} Registro de Portafolio {% endblock title%}
{% load static %}


{% block content %}
<h2>Registrar Portafolio</h2>
<form method="post">
    {% include 'myapp/_form.html' %}
    <button type="submit" class = "btn btn-primary">Guardar</button>
</form>

{% endblock %}

mi_portal_web/my_app/templates/myapp/services.html
{% extends 'myapp/base.html' %}
{% block title %} home {% endblock title%}
{% load static %}

{% block content %}
    <h1>Bienvenidos a esta página</h1>
    <p>Esta es la página de Service</p>
    
{% endblock %}

mi_portal_web/my_app/templates/myapp/testimonio_register.html
{% extends 'myapp/base.html' %}
{% block title %} Registro de Testimonios {% endblock title%}
{% load static %}


{% block content %}
<h2>Registrar Testimonio</h2>
<form method="post">
    {% include 'myapp/_form.html' %}
    <button type="submit" class = "btn btn-primary">Guardar</button>
</form>

{% endblock %}

mi_portal_web/my_app/templates/myapp/testimonios.html
{% extends 'myapp/base.html' %} 
{% block title%} Testimonios {% endblock title%}
{% load static %} 
{%block content%}
<h1>Testimonios</h1>
<div class="row">
{%if testimonails%}
  {%for testimonio in testimonios%}
    <div class="card" style="width: 18rem">
      <h5 class="card-title">{{testimonio.nombre }}</h5>
    <div class="card-body">
    <p class="card-text">{{ testimonio.puesto }}<span>{{ testimonio.empresa }}</span></p>
      <p class="card-text">{{ testimonio.descripcion }}</p>

      <a href="{% url 'testmonio_register' %}">Agrega un testimonio</a>
    </div>
  </div>
  {%endfor %}
  {% else %}
  <p>No hay testimonio al momento</p>
{%endif%}
</div>

{% endblock content %}


{% comment %} {% extends 'myapp/base.html' %}
{% block title %} home {% endblock title %}
{% load static %}

{% block content %}
<h1>Bienvenidos a esta página</h1>
<p>Esta es la página de Testimonios de Clientes</p>
<div class="row">
    {% if testimonios %}
        {% for testimonio in testimonios %}
        <div class="card" style="width: 18rem;">
            <img src={% static project.image %} class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ testimonio.name }}</h5>
              <p class="card-text">{{ testimonio.description }}</p>
              <p class="card-text">{{ testimonio.puesto }}</p>
              <p class="card-text">{{ testimonio.empresa }}</p>
              <a href="{{ testimonio.url }}" target="_blank" class="btn btn-primary">Visitar el sitio</a>
            </div>
          </div>
        {% endfor %}
    {% else %}
        <p>No hay testimonios disponibles en este momento.</p>
    {% endif %}
</div>
{% endblock %} {% endcomment %}